### PR TITLE
Update Chromium to version 131.0.6778.70

### PR DESCRIPTION
**Pull request by artem-trofimov**
In this changeset we upgrade Chromium to version 131.0.6778.70.

Please review the modified Chromium licenses.

### CODE REVIEW

**Comment by vladimir-ikryanov** [comment]
@anzhelika-zarandiia @Olena-Brovkina @oleksandra-moiseieva When can we expect your review? This PR holds release and it's important to review it as soon as you can.

**Comment by anzhelika-zarandiia** [comment]
> @anzhelika-zarandiia @Olena-Brovkina @oleksandra-moiseieva When can we expect your review? This PR holds release and it's important to review it as soon as you can.

@vladimir-ikryanov as far as I understand, this request depends on issue #67, which is in progress now due to a number of new licenses added, which need an additional verification.

We will prioritise this request in order to finish it as soon as possible.

**Comment by anzhelika-zarandiia** [comment]
@vladimir-ikryanov, @artem-trofimov, we are checking new licenses and need your assistance with the following components.

## [Libxml](https://github.com/TeamDev-IP/Chromium-Licences/blob/131.0.6778.70/chromium-licenses/third_party/libxml/src/Copyright)

Please extract dict.c and list.c files. 

We already did it for this [PR](https://github.com/TeamDev-IP/Chromium-Licences/pull/67).

## [Read-fonts-0.22.5](https://github.com/TeamDev-IP/Chromium-Licences/tree/131.0.6778.70/chromium-licenses/third_party/rust/chromium_crates_io/vendor/read-fonts-0.22.5)

License file for this component does not include license text or link to the license text. 

We need to include the license text. Please let's discuss.

## [skrifa-0.23.1](https://github.com/TeamDev-IP/Chromium-Licences/tree/131.0.6778.70/chromium-licenses/third_party/rust/chromium_crates_io/vendor/skrifa-0.23.1)

License file for this component does not include license text or link to the license text. 

We need to include the license text. Please let's discuss.

**Comment by anzhelika-zarandiia** [comment]
@artem-trofimov, thank you for the details and added files.

As to the [read-fonts-0.23.2](https://source.chromium.org/chromium/chromium/src/+/refs/tags/132.0.6834.15:third_party/rust/chromium_crates_io/vendor/read-fonts-0.23.2/LICENSE-APACHE) and [skrifa-0.24.1](https://source.chromium.org/chromium/chromium/src/+/refs/tags/132.0.6834.15:third_party/rust/chromium_crates_io/vendor/skrifa-0.24.1/LICENSE-APACHE) there is no need to add the license texts manually.

**Comment by vladimir-ikryanov** [comment]
@anzhelika-zarandiia let's avoid adding the license texts manually. If the license is absent in the Chromium source code, we should mention it in our table, but we shouldn't search for the license text. In Chromium 132 they will add the absent license text for the `read-fonts` and `skrifa` components. When we upgrade Chromium to version 132, the license text for these components will be added automatically.

Chromium team is actively working on resolving such issues with the missing licenses. We should trust the Chromium team and rely on their work regarding collecting the open source component used by Chromium.

**Comment by anzhelika-zarandiia** [comment]
@vladimir-ikryanov, thank you. We have the same understanding on this matter.

**Review by anzhelika-zarandiia — APPROVED** [review]

**Pull request merged**
