### PR TITLE
Update Chromium to version 123.0.6312.87

### PR DESCRIPTION
**Pull request by artem-trofimov**
In this changeset we upgrade Chromium to version 123.0.6312.87.

Please review the modified Chromium licenses.

### CODE REVIEW

**Comment by vladimir-ikryanov** [comment]
@anzhelika-zarandiia what's the progress of the licenses review? It blocks the product release.

**Comment by anzhelika-zarandiia** [comment]
@vladimir-ikryanov revision is almost done.

**Review by anzhelika-zarandiia — APPROVED** [review]

**Comment by vladimir-ikryanov** [comment]
@anzhelika-zarandiia where's the link to the table we publish in our documentation?

**Comment by vladimir-ikryanov** [comment]
Here's the link: https://docs.google.com/spreadsheets/d/1INKzOCfYxYzZZidgguTajaShOehYylZIC1tILMCTxWo

**Pull request merged**
