### PR TITLE
Update Chromium licenses [part II]

### PR DESCRIPTION
**Pull request by artem-trofimov**
This is part II of #66.

This changeset contains files that have been moved or renamed within the component project directory, as well as new license files that were previously undetected.

### CODE REVIEW

**Comment by anzhelika-zarandiia** [comment]
@artem-trofimov @vladimir-ikryanov we are reviewing the licenses and need your assistance in the following matters. I will split questions into two comments.

[ffmpeg component ](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/ffmpeg/CREDITS.chromium)

Please confirm we do not use the following libraries, licensed under LGPL v.3.

- gmp
- libaribb24
- liblensfun

[Hunspell component 
](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/hunspell/COPYING.MPL)

This component is licensed under the MPL license, which requires the disclosure of source code of modifications. 

Please confirm we do not make modifications to this component.

[snappy component
](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/snappy/src/COPYING)

This component is licensed under 3-clause BSD license, while some of the benchmark data in testdata/ is licensed differently.

Fireworks.jpeg is licensed by Creative Commons Attribution 3.0 license, and paper-100k.pdf is under the Creative Commons Attribution license 4.0

Please let me know whether we use such files.

[libxml component ](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/libxml/src/Copyright)

This component is licensed under the MIT license, while mentions dict.c and list.c files not covered by this license.
We do not have licenses for these files, could you please extract it?

**Comment by anzhelika-zarandiia** [comment]
Following up on my previous comment.

We have the following new components, licensed under the LGPL license:

[libusb](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/libusb/src/COPYING) 
[speech-dispatcher 
](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/speech-dispatcher/COPYING.LGPL)[wayland-protocols/gtk
](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/wayland-protocols/gtk/COPYING)[wayland-protocols/kde](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/wayland-protocols/kde/COPYING.LIB)

Please let me know whether we use these components. If yes, please confirm that we do not modify such components, but link them or compile with our code.

We are also checking [wtl component](https://github.com/TeamDev-IP/Chromium-Licences/blob/new-licenses-part2/chromium-licenses/third_party/wtl/Ms-PL.txt), to make sure our Product Agreements comply with requirements of wtl license, as required by its terms.

**Comment by vladimir-ikryanov** [comment]
@anzhelika-zarandiia we will take a look and get back to you.

**Comment by vladimir-ikryanov** [comment]
@anzhelika-zarandiia please take a look at the results of our investigation regarding the new components in https://github.com/TeamDev-IP/Chromium-Licences/pull/67#issuecomment-2493720055

**Comment by anzhelika-zarandiia** [comment]
> @anzhelika-zarandiia please take a look at the results of our investigation regarding the new components in [#67 (comment)](https://github.com/TeamDev-IP/Chromium-Licences/pull/67#issuecomment-2493720055)

@vladimir-ikryanov, thank you, working on it.

**Review by anzhelika-zarandiia — APPROVED** [review]

**Pull request merged**
